name: Greenifier
main: Greenifier\Greenifier
version: 0.0.1
description: Smashes The Black Grass Bug On Imported PocketMine Worlds!

commands:
 greenify:
  description: "Sets grass blocks green."
  usage: "/greenify"
  permission: "Greenifier.command.greenify"

permissions:
 Greenifier:
  default: op
  description: "Allows using all the Greenifier functionality."
  children:
   Greenifier.command:
    default: op
    description: "Allows using the greenify command."
    children:
     Greenifier.command.greenify:
      default: op
